version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
    environment:
      - PARSE_APP_ID=ulink_app
      - PARSE_MASTER_KEY=ulink_master_key
  parse-dashboard:
    image: 'bitnami/parse-dashboard:latest'
    ports:
      - '80:40400'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - mongodb
      - parse
    environment:
      - PARSE_DASHBOARD_USER=ulink
      - PARSE_DASHBOARD_PASSWORD=ulink
      - PARSE_APP_ID=ulink_app
      - PARSE_MASTER_KEY=ulink_master_key

volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local